### ISSUE TITLE
Raise if put operation doesn't complete within timeout

### ISSUE THREAD

**Issue by AbbyGi** [BNL-ATF/profile_atf#7]
We should raise an exception after [this block](https://github.com/BNL-ATF/profile_atf/blob/66059e47a0756919b959b04c59177c0c3f8365f0/startup/10-devices.py#L194-L199) if the put operation couldn't be completed within the timeout allowed.

**Comment by mrakitin** [comment]
Implemented via https://github.com/BNL-ATF/atfdb/pull/5.
